(cl:defpackage SerialDriver-srv
  (:use )
  (:export
   "SERIAL_SERVICE"
   "<SERIAL_SERVICE-REQUEST>"
   "SERIAL_SERVICE-REQUEST"
   "<SERIAL_SERVICE-RESPONSE>"
   "SERIAL_SERVICE-RESPONSE"
   "SERIAL_WRITE_SERVICE"
   "<SERIAL_WRITE_SERVICE-REQUEST>"
   "SERIAL_WRITE_SERVICE-REQUEST"
   "<SERIAL_WRITE_SERVICE-RESPONSE>"
   "SERIAL_WRITE_SERVICE-RESPONSE"
  ))

