/* Auto-generated by genmsg_cpp for file /home/frs2012-5/fuerte_workspace/botI/msg/position_in_row.msg */
#ifndef BOTI_MESSAGE_POSITION_IN_ROW_H
#define BOTI_MESSAGE_POSITION_IN_ROW_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace botI
{
template <class ContainerAllocator>
struct position_in_row_ {
  typedef position_in_row_<ContainerAllocator> Type;

  position_in_row_()
  : header()
  , x(0.0)
  , gamma(0.0)
  {
  }

  position_in_row_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , x(0.0)
  , gamma(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _x_type;
  float x;

  typedef float _gamma_type;
  float gamma;


  typedef boost::shared_ptr< ::botI::position_in_row_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::botI::position_in_row_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct position_in_row
typedef  ::botI::position_in_row_<std::allocator<void> > position_in_row;

typedef boost::shared_ptr< ::botI::position_in_row> position_in_rowPtr;
typedef boost::shared_ptr< ::botI::position_in_row const> position_in_rowConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::botI::position_in_row_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::botI::position_in_row_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace botI

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::botI::position_in_row_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::botI::position_in_row_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::botI::position_in_row_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b072d57812e00fb344900c38bb333420";
  }

  static const char* value(const  ::botI::position_in_row_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb072d57812e00fb3ULL;
  static const uint64_t static_value2 = 0x44900c38bb333420ULL;
};

template<class ContainerAllocator>
struct DataType< ::botI::position_in_row_<ContainerAllocator> > {
  static const char* value() 
  {
    return "botI/position_in_row";
  }

  static const char* value(const  ::botI::position_in_row_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::botI::position_in_row_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 x\n\
float32 gamma \n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::botI::position_in_row_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::botI::position_in_row_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::botI::position_in_row_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::botI::position_in_row_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.x);
    stream.next(m.gamma);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct position_in_row_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::botI::position_in_row_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::botI::position_in_row_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "gamma: ";
    Printer<float>::stream(s, indent + "  ", v.gamma);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BOTI_MESSAGE_POSITION_IN_ROW_H

