(cl:in-package fmMsgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          BRUSHLESSCOUNTER-VAL
          BRUSHLESSCOUNTER
          BRUSHLESSCOUNTERRELATIVE-VAL
          BRUSHLESSCOUNTERRELATIVE
          BATTERYVOLTAGE-VAL
          BATTERYVOLTAGE
          BATTERYAMPERE-VAL
          BATTERYAMPERE
          TRACKDISTANCE-VAL
          TRACKDISTANCE
          TRACKDISTANCERELATIVE-VAL
          TRACKDISTANCERELATIVE
))