(cl:in-package fmMsgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME_RECV-VAL
          TIME_RECV
          TIME-VAL
          TIME
          LAT-VAL
          LAT
          LON-VAL
          LON
          UTM_ZONE_NUM-VAL
          UTM_ZONE_NUM
          UTM_ZONE_LET-VAL
          UTM_ZONE_LET
          UTM_N-VAL
          UTM_N
          UTM_E-VAL
          UTM_E
          ALT-VAL
          ALT
          FIX-VAL
          FIX
          SAT-VAL
          SAT
          HDOP-VAL
          HDOP
          GEOID_HEIGHT-VAL
          GEOID_HEIGHT
))