(cl:defpackage fmMsgs-msg
  (:use )
  (:export
   "<GYROSCOPE>"
   "GYROSCOPE"
   "<RTQ_COMMAND>"
   "RTQ_COMMAND"
   "<CAN>"
   "CAN"
   "<ROW>"
   "ROW"
   "<GPS_STATE>"
   "GPS_STATE"
   "<SERIAL>"
   "SERIAL"
   "<ACCELEROMETER>"
   "ACCELEROMETER"
   "<RTQ>"
   "RTQ"
   "<ENCODER>"
   "ENCODER"
   "<GPGGA>"
   "GPGGA"
   "<STEERING_ANGLE_CMD>"
   "STEERING_ANGLE_CMD"
   "<CLAAS_ROW_CAM>"
   "CLAAS_ROW_CAM"
   "<MOTOR_STATUS>"
   "MOTOR_STATUS"
   "<MAGNETOMETER>"
   "MAGNETOMETER"
   "<RTQ_LAMP_COMMAND>"
   "RTQ_LAMP_COMMAND"
  ))

